example-facets/example_project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", TemplateView.as_view(template_name="base.html")),
    path("traffic-stops/", include("traffic_stops.urls")),
    path("firearms/", include("firearms.urls")),
    path("__reload__/", include("django_browser_reload.urls")),
    path("films/", include("films.urls")),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

example-facets/films/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.FilmListView.as_view(), name="films-list"),
    path("manual/", views.ManualFilmListView.as_view(), name="manual-films-list"),
]

example-facets/films/models.py
from django.db import models


class Film(models.Model):
    show_id = models.CharField(max_length=1000)
    type = models.CharField(max_length=1000)
    title = models.CharField(max_length=1000)
    director = models.CharField(max_length=1000)
    cast = models.TextField()
    country = models.CharField(max_length=1000)
    date_added = models.DateField()
    release_year = models.DateField()
    rating = models.CharField(max_length=15)
    duration = models.CharField(max_length=1000)
    listed_in = models.TextField()
    description = models.TextField(default="")
    genres = models.ManyToManyField("films.Genre")

    def __str__(self):
        return self.title


class Genre(models.Model):
    name = models.CharField(max_length=1000)

    def __str__(self):
        return self.name

example-facets/traffic_stops/models.py
from django.db import models

PURPOSE_CHOICES = (
    (1, "Speed Limit Violation"),
    (2, "Stop Light/Sign Violation"),
    (3, "Driving While Impaired"),
    (4, "Safe Movement Violation"),
    (5, "Vehicle Equipment Violation"),
    (6, "Vehicle Regulatory Violation"),
    (7, "Seat Belt Violation"),
    (8, "Investigation"),
    (9, "Other Motor Vehicle Violation"),
    (10, "Checkpoint"),
)

ACTION_CHOICES = (
    (1, "Verbal Warning"),
    (2, "Written Warning"),
    (3, "Citation Issued"),
    (4, "On-View Arrest"),
    (5, "No Action Taken"),
)


PERSON_TYPE_CHOICES = (("D", "Driver"), ("P", "Passenger"))


GENDER_CHOICES = (("M", "Male"), ("F", "Female"))


ETHNICITY_CHOICES = (("H", "Hispanic"), ("N", "Non-Hispanic"))


RACE_CHOICES = (
    ("A", "Asian"),
    ("B", "Black"),
    ("I", "Native American"),
    ("U", "Other"),
    ("W", "White"),
)

SEARCH_TYPE_CHOICES = (
    (1, "Consent"),
    (2, "Search Warrant"),
    (3, "Probable Cause"),
    (4, "Search Incident to Arrest"),
    (5, "Protective Frisk"),
)


SEARCH_BASIS_CHOICES = (
    ("ER", "Erratic/Suspicious Behavior"),
    ("OB", "Observation of Suspected Contraband"),
    ("OI", "Other Official Information"),
    ("SM", "Suspicious Movement"),
    ("TIP", "Informant Tip"),
    ("WTNS", "Witness Observation"),
)


class Stop(models.Model):
    stop_id = models.PositiveIntegerField(primary_key=True)
    agency_description = models.CharField(max_length=100)
    agency = models.ForeignKey(
        "Agency", null=True, related_name="stops", on_delete=models.CASCADE
    )
    date = models.DateTimeField(db_index=True)
    purpose = models.PositiveSmallIntegerField(choices=PURPOSE_CHOICES)
    action = models.PositiveSmallIntegerField(choices=ACTION_CHOICES)
    driver_arrest = models.BooleanField(default=False)
    passenger_arrest = models.BooleanField(default=False)
    encounter_force = models.BooleanField(default=False)
    engage_force = models.BooleanField(default=False)
    officer_injury = models.BooleanField(default=False)
    driver_injury = models.BooleanField(default=False)
    passenger_injury = models.BooleanField(default=False)
    officer_id = models.CharField(max_length=15)  # todo: keys
    stop_location = models.CharField(max_length=15)  # todo: keys
    stop_city = models.CharField(max_length=20)


class Person(models.Model):
    class Race(models.TextChoices):
        ASIAN = "A", "Asian"
        BLACK = "B", "Black"
        NATVE_AMERICAN = "I", "Native American"
        OTHER = "U", "Other"
        WHITE = "W", "White"
        HISPANIC = "H", "Hispanic"

    class Ethnicity(models.TextChoices):
        HISPANIC = "H", "Hispanic"
        NON_HISPANIC = "N", "Non-Hispanic"

    person_id = models.IntegerField(primary_key=True)
    stop = models.ForeignKey(Stop, on_delete=models.CASCADE)
    type = models.CharField(max_length=2, choices=PERSON_TYPE_CHOICES)
    age = models.PositiveSmallIntegerField()
    gender = models.CharField(max_length=2, choices=GENDER_CHOICES)
    ethnicity = models.CharField(max_length=2, choices=Ethnicity.choices)
    race = models.CharField(max_length=2, choices=Race.choices)


class Search(models.Model):
    search_id = models.IntegerField(primary_key=True)
    stop = models.ForeignKey(Stop, on_delete=models.CASCADE)
    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    type = models.PositiveSmallIntegerField(choices=SEARCH_TYPE_CHOICES)
    vehicle_search = models.BooleanField(default=False)
    driver_search = models.BooleanField(default=False)
    passenger_search = models.BooleanField(default=False)
    property_search = models.BooleanField(default=False)
    vehicle_siezed = models.BooleanField(default=False)
    personal_property_siezed = models.BooleanField(default=False)
    other_property_sized = models.BooleanField(default=False)


class Contraband(models.Model):
    contraband_id = models.IntegerField(primary_key=True)
    search = models.ForeignKey(Search, on_delete=models.CASCADE)
    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    stop = models.ForeignKey(Stop, on_delete=models.CASCADE)
    ounces = models.FloatField(default=0, null=True)
    pounds = models.FloatField(default=0, null=True)
    pints = models.FloatField(default=0, null=True)
    gallons = models.FloatField(default=0, null=True)
    dosages = models.FloatField(default=0, null=True)
    grams = models.FloatField(default=0, null=True)
    kilos = models.FloatField(default=0, null=True)
    money = models.FloatField(default=0, null=True)
    weapons = models.FloatField(default=0, null=True)
    dollar_amount = models.FloatField(default=0, null=True)


class SearchBasis(models.Model):
    search_basis_id = models.IntegerField(primary_key=True)
    search = models.ForeignKey(Search, on_delete=models.CASCADE)
    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    stop = models.ForeignKey(Stop, on_delete=models.CASCADE)
    basis = models.CharField(max_length=4, choices=SEARCH_BASIS_CHOICES)


class Agency(models.Model):
    name = models.CharField(max_length=255)
    census_profile_id = models.CharField(max_length=16, blank=True, default="")
    last_reported_stop = models.DateField(null=True)

    class Meta(object):
        verbose_name_plural = "Agencies"

    def __str__(self):
        return self.name

example-facets/films/views.py
from django.db.models import Count
from django.views.generic.list import ListView

from .filters import FilmFilterSet, SimpleFilmFilterSet
from .models import Film


class FilmListView(ListView):
    # https://docs.djangoproject.com/en/4.0/ref/class-based-views/generic-display/#listview

    model = Film
    ordering = "title"
    paginate_by = 25

    def get_queryset(self):
        qs = super().get_queryset()
        self.filter_set = FilmFilterSet(self.request.GET, queryset=qs)
        return self.filter_set.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["filter"] = self.filter_set
        return context


class ManualFilmListView(ListView):
    # https://docs.djangoproject.com/en/4.0/ref/class-based-views/generic-display/#listview

    model = Film
    paginate_by = 5
    template_name_suffix = "_list_manual"

    def get_queryset(self):
        qs = super().get_queryset()
        self.filter_set = SimpleFilmFilterSet(self.request.GET, queryset=qs)
        return self.filter_set.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["film_types"] = (
            self.get_queryset().values("type").annotate(count=Count("id"))
        )
        return context

example-facets/films/templates/films/film_list.html
{% extends 'base.html' %}
{% load search_tags %}

{% block title %}Films{% endblock %}

{% block content %}
<!-- Posts Section -->
<section class="w-full md:w-2/3 flex flex-col items-center px-3">
  <div class="overflow-x-auto relative">
    <table
      class="w-full table text-sm text-left text-gray-500 dark:text-gray-400"
    >
      <thead
        class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400"
      >
        <tr>
          <th scope="col" class="py-3 px-6">Title</th>
          <th scope="col" class="py-3 px-6">Type</th>
          <th scope="col" class="py-3 px-6">Genre</th>
          <th scope="col" class="py-3 px-6">Description</th>
          <th scope="col" class="py-3 px-6">Cast</th>
        </tr>
      </thead>
      <tbody>
        {% for film in object_list %}
        <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
          <th
            scope="row"
            class="py-4 px-6 font-medium text-gray-900 dark:text-white"
          >
            {{ film.title }} {% if film.rank %}{{ film.rank }}{% endif %}
          </th>
          <td class="py-4 px-6">{{ film.type }}</td>
          <td class="py-4 px-6">{{ film.listed_in }}</td>
          <td class="py-4 px-6">{{ film.description|safe }}</td>
          <td class="py-4 px-6">{{ film.cast }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

  <!-- Pagination -->
  <div class="flex flex-col items-center">
    <div class="inline-flex mt-2 xs:mt-0">
      <!-- Buttons -->
      <a
        href="{% if page_obj.has_previous %}{{ request.path }}?page={{ page_obj.previous_page_number }}{% endif %}"
        class="inline-flex items-center py-2 px-4 text-sm disabled font-medium text-white bg-gray-800 rounded-l hover:bg-gray-900 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white"
      >
        <svg
          aria-hidden="true"
          class="mr-2 w-5 h-5"
          fill="currentColor"
          viewBox="0 0 20 20"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            fill-rule="evenodd"
            d="M7.707 14.707a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 1.414L5.414 9H17a1 1 0 110 2H5.414l2.293 2.293a1 1 0 010 1.414z"
            clip-rule="evenodd"
          ></path>
        </svg>
        Prev
      </a>
      <a
        href="{% if page_obj.has_next %}{{ request.path }}?page={{ page_obj.next_page_number }}{% endif %}"
        class="inline-flex items-center py-2 px-4 text-sm font-medium text-white bg-gray-800 rounded-r border-0 border-l border-gray-700 hover:bg-gray-900 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white"
      >
        Next
        <svg
          aria-hidden="true"
          class="ml-2 w-5 h-5"
          fill="currentColor"
          viewBox="0 0 20 20"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            fill-rule="evenodd"
            d="M12.293 5.293a1 1 0 011.414 0l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-2.293-2.293a1 1 0 010-1.414z"
            clip-rule="evenodd"
          ></path>
        </svg>
      </a>
    </div>
  </div>
</section>

<!-- Sidebar Section -->
<aside class="w-full md:w-1/3 flex flex-col items-center px-3">
  <div class="w-full bg-white shadow flex flex-col px-6 pb-6 dark:bg-slate-600">
    <div class="w-full pt-4 mb-4">
      <h1 class="font-serif text-2xl border-b-4">Netflix films and tv-shows</h1>
      <p class="mt-1 max-w-2xl text-sm text-gray-500">Source: <a target="_blank" class="no-underline hover:underline" href="https://www.kaggle.com/datasets/shivamb/netflix-shows">Kaggle netflix-shows</a></p>
    </div>
    <form method="get" action="." class="mb-3">
      <div class="flex">
        <div class="relative w-full">
          <input type="search" id="id_search" name="search"{% if filter.form.search.value != None %} value="{{ filter.form.search.value|stringformat:'s' }}"{% endif %} class="block p-2.5 w-full z-20 text-sm text-gray-900 bg-gray-50 rounded-lg border focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:border-blue-500" placeholder="Search">
          <button type="submit" class="absolute top-0 right-0 p-2.5 text-sm font-medium text-white bg-blue-700 rounded-r-lg border border-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"><svg aria-hidden="true" class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path></svg></button>
        </div>
      </div>
    </form>
    {% show_facets filter %}
  </div>
</aside>
{% endblock %}

example-facets/films/templates/films/film_list_manual.html
{% extends 'base.html' %}
{% load search_tags %}

{% block content %}
<ul>
{% for film in object_list %}
    <li>{{ film.title }}</li>
{% endfor %}
</ul>

{% show_facets filter %}
{% endblock %}

example-facets/films/templates/films/films_list.html
{% extends 'base.html' %}
{% load search_tags %}

{% block title %}Films{% endblock %}

{% block content %}
<!-- Posts Section -->
<section class="w-full md:w-2/3 flex flex-col items-center px-3">
  <div class="overflow-x-auto relative">
    <table
      class="w-full table text-sm text-left text-gray-500 dark:text-gray-400"
    >
      <thead
        class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400"
      >
        <tr>
          <th scope="col" class="py-3 px-6">Title</th>
          <th scope="col" class="py-3 px-6">Type</th>
          <th scope="col" class="py-3 px-6">Genre</th>
          <th scope="col" class="py-3 px-6">Director</th>
          <th scope="col" class="py-3 px-6">Cast</th>
          <th scope="col" class="py-3 px-6">Country</th>
          <th scope="col" class="py-3 px-6">Release Year</th>
        </tr>
      </thead>
      <tbody>
        {% for film in object_list %}
        <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
          <th
            scope="row"
            class="py-4 px-6 font-medium text-gray-900 whitespace-nowrap dark:text-white"
          >
            {{ stop.date }}
          </th>
          <td class="py-4 px-6">{{ stop.driver_race }}</td>
          <td class="py-4 px-6">
            {% get_facet_display filter 'driver_gender' stop.driver_gender %}
          </td>
          <td class="py-4 px-6">{{ stop.officer_id }}</td>
          <td class="py-4 px-6">{{ stop.get_purpose_display }}</td>
          <td class="py-4 px-6">
            {% if stop.search_type %}{% get_facet_display filter 'search_type' stop.search_type %}{% endif %}
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

  <!-- Pagination -->
  <div class="flex flex-col items-center">
    <div class="inline-flex mt-2 xs:mt-0">
      <!-- Buttons -->
      <a
        href="{% if page_obj.has_previous %}{{ request.path }}?page={{ page_obj.previous_page_number }}{% endif %}"
        class="inline-flex items-center py-2 px-4 text-sm disabled font-medium text-white bg-gray-800 rounded-l hover:bg-gray-900 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white"
      >
        <svg
          aria-hidden="true"
          class="mr-2 w-5 h-5"
          fill="currentColor"
          viewBox="0 0 20 20"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            fill-rule="evenodd"
            d="M7.707 14.707a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 1.414L5.414 9H17a1 1 0 110 2H5.414l2.293 2.293a1 1 0 010 1.414z"
            clip-rule="evenodd"
          ></path>
        </svg>
        Prev
      </a>
      <a
        href="{% if page_obj.has_next %}{{ request.path }}?page={{ page_obj.next_page_number }}{% endif %}"
        class="inline-flex items-center py-2 px-4 text-sm font-medium text-white bg-gray-800 rounded-r border-0 border-l border-gray-700 hover:bg-gray-900 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white"
      >
        Next
        <svg
          aria-hidden="true"
          class="ml-2 w-5 h-5"
          fill="currentColor"
          viewBox="0 0 20 20"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            fill-rule="evenodd"
            d="M12.293 5.293a1 1 0 011.414 0l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-2.293-2.293a1 1 0 010-1.414z"
            clip-rule="evenodd"
          ></path>
        </svg>
      </a>
    </div>
  </div>
</section>

<!-- Sidebar Section -->
<aside class="w-full md:w-1/3 flex flex-col items-center px-3">
  <div class="w-full bg-white shadow flex flex-col px-6 pb-6 dark:bg-slate-600">
    <div class="w-full pt-4 mb-4">
      <h1 class="font-serif text-2xl border-b-4">North Carolina Traffic Stops</h1>
      <p class="mt-1 max-w-2xl text-sm text-gray-500">Source: <a target="_blank" class="no-underline hover:underline" href="https://nccopwatch.org/">NC CopWatch</a></p>
    </div>
    {% show_facets filter %}
  </div>
</aside>
{% endblock %}